version: '2'
services:
  academy-app:
    container_name: ${CN}
    image: ${DIN}:${DIV}
    env_file: .env
    working_dir: /var/www
    ports:
      - '1012:1012'
      - '80:8080'
      - '443:8443'
    networks:
      - dclm
    volumes:
      - ./moodle_code:/bitnami/moodle
      - ./moodle_data:/bitnami/moodledata
      - /etc/letsencrypt/live/dclm.org/fullchain.pem:/certs/server.crt
      - /etc/letsencrypt/live/dclm.org/privkey.pem:/certs/server.key
    restart: always

networks:
  dclm:
    name: dclm
    external: true