version: '2'
services:
  academy-app:
    container_name: ${CN}
    image: ${DIN}:${DIV}
    env_file: .env
    ports:
      - '1012:1012'
    networks:
      - bams
    volumes:
      - ./app:/var/www
      - ./data:/var/data
      - ../ops/docker/ngx/academy.conf:/etc/nginx/sites-enabled/default
      - ~/dev/keys/mac/bams.pem:/var/ssl/cert.pem
      - ~/dev/keys/mac/bams-key.pem:/var/ssl/key.pem
    restart: always

networks:
  bams:
    name: bams
    external: true
