version: '2'
services:
  academy-app:
    container_name: ${CN}
    image: ${DIN}:${DIV}
    env_file: .env
    working_dir: /var/www
    ports:
      - '1012:1012'
    networks:
      - dclm
    volumes:
      - ./app:/var/www
      - ./data:/var/data
      - /etc/letsencrypt/live/dclm.org/fullchain.pem:/var/ssl/cert.pem
      - /etc/letsencrypt/live/dclm.org/privkey.pem:/var/ssl/key.pem
    restart: always

networks:
  dclm:
    name: dclm
    external: true