version: '2'
services:
  moodle-app:
    container_name: moodle-app
    image: docker.io/bitnami/moodle:4.1
    env_file: .env
    # working_dir: /var/www
    ports:
      - '1012:8443'
    networks:
      - bams
    volumes:
      - ./data/moodle_data:/bitnami/moodle'
      - ./data/moodledata_data:/bitnami/moodledata'
      - ~/dev/keys/mac/bams.pem:/certs/server.crt
      - ~/dev/keys/mac/bams-key.pem:/certs/server.key

networks:
  bams:
    name: bams
    external: true
